const messages = {"work": {"en": "Selected work", "es": "Proyectos"}, "about": {"en": "About", "es": "Sobre mí"}, "contact": {"en": "Contact", "es": "Contacto"}, "eyebrow": {"en": "Software · Automation · Digital twins", "es": "Software · Automatización · Gemelos digitales"}, "title": {"en": "Complex systems.\nClear possibilities.", "es": "Sistemas complejos.\nPosibilidades claras."}, "intro": {"en": "I build digital tools to explore infrastructure, connect information and make technical ideas tangible.", "es": "Desarrollo herramientas digitales para explorar infraestructura, conectar información y dar forma a ideas técnicas."}, "talk": {"en": "Let’s discuss your project ↗", "es": "Hablemos de tu proyecto ↗"}, "explore": {"en": "Explore my work ↓", "es": "Explora mi trabajo ↓"}, "selected": {"en": "01 / Selected work", "es": "01 / Proyecto destacado"}, "built": {"en": "An idea, made interactive.", "es": "Una idea, hecha interactiva."}, "private": {"en": "Private preview", "es": "Vista previa privada"}, "desc": {"en": "Explore how IT load, electrical distribution and cooling work together. A configurable data center simulator with detailed equipment views.", "es": "Explora cómo interactúan la carga IT, la distribución eléctrica y la refrigeración. Un simulador configurable de centros de datos con vistas detalladas de equipos."}, "f1": {"en": "Equipment-based configuration", "es": "Configuración por equipos"}, "f2": {"en": "Power and cooling diagrams", "es": "Diagramas eléctricos y de refrigeración"}, "f3": {"en": "English and Spanish interface", "es": "Interfaz en inglés y español"}, "open": {"en": "Open simulator ↗", "es": "Abrir simulador ↗"}, "access": {"en": "Access is limited to authorized email addresses.", "es": "Acceso limitado a correos autorizados."}, "focus": {"en": "02 / Approach", "es": "02 / Enfoque"}, "heading": {"en": "From technical questions\nto practical tools.", "es": "De preguntas técnicas\na herramientas prácticas."}, "bio": {"en": "My work brings together software, automation and infrastructure. This lab is where I turn ideas into working prototypes and explore how systems behave.", "es": "Mi trabajo conecta software, automatización e infraestructura. En este laboratorio convierto ideas en prototipos funcionales y exploro el comportamiento de los sistemas."}, "topics": {"en": "Current areas of exploration", "es": "Áreas de exploración"}, "a": {"en": "Digital twins", "es": "Gemelos digitales"}, "b": {"en": "Industrial automation", "es": "Automatización industrial"}, "c": {"en": "AI tools", "es": "Herramientas de IA"}, "d": {"en": "3D prototyping", "es": "Prototipado 3D"}, "next": {"en": "03 / Let’s connect", "es": "03 / Conversemos"}, "question": {"en": "What are you working on?", "es": "¿En qué estás trabajando?"}, "invitation": {"en": "Tell me about your project, your technical challenge or the idea you want to explore.", "es": "Cuéntame sobre tu proyecto, tu reto técnico o la idea que quieres explorar."}};
function setLanguage(language){
 const lang=language==='es'?'es':'en';
 document.documentElement.lang=lang;
 document.querySelectorAll('[data-i18n]').forEach(el=>{el.textContent=messages[el.dataset.i18n][lang]});
 document.querySelectorAll('[data-language]').forEach(el=>el.setAttribute('aria-pressed',String(el.dataset.language===lang)));
 document.querySelector('meta[name="description"]').content=lang==='es'?'Franklin Sandoval — software, automatización y gemelos digitales. Explora el simulador DC + BMS.':'Franklin Sandoval — software, automation and digital twins. Explore the DC + BMS Simulator.';
 try{localStorage.setItem('franklin-site-language',lang)}catch{}
}
let language='en';try{language=localStorage.getItem('franklin-site-language')||'en'}catch{}
setLanguage(language);
document.querySelectorAll('[data-language]').forEach(el=>el.addEventListener('click',()=>setLanguage(el.dataset.language)));
