const FTA_RUBRIC={
networking:{label:"Networking",qs:[1,2,3,4,5,6,7,8,9,10],terms:{1:["router","gateway","different subnet","different network"],2:["layer 2","mac","router","layer 3"],3:["dns","ip","arp","tcp"],4:["ip","mac"],5:["access","vlan","trunk","802.1q"],6:["routing","router","layer 3","svi"],7:["loop","broadcast"],8:["192.168.50.64","192.168.50.95","192.168.50.65","192.168.50.94","30"],9:["tcp","reliable","udp","connectionless"],10:["443","port","firewall","service","listen"]}},
linux:{label:"Linux",qs:[11,12,13,14,15],terms:{11:["ip addr","ip a","ifconfig"],12:["grep","find"],13:["grep","find","systemctl","journalctl"],14:["ss","netstat","5432","listen"],15:["chmod","permission","chown","owner","sudo"]}},
sql:{label:"SQL / PostgreSQL",qs:[16,17,18,19,20],terms:{16:["select","from","servers","where","status","down"],17:["unique","identify","row"],18:["table","join","related"],19:["select","read","update","delete"],20:["service","port","5432","firewall","network","listen"]}},
bms:{label:"BMS / BACnet",qs:[21,22,23,24,25],terms:{21:["sensor","point","trend","communication","controller"],22:["alarm","trend","point"],23:["protocol","building","automation","communication"],24:["analog input","analog output","binary input","binary output"],25:["device","network","power","controller","communication"]}},
troubleshooting:{label:"Troubleshooting",qs:[26],terms:{26:["hypothesis","test","443","firewall","service","listen","next"]}}
};
function getAnswers(){try{return JSON.parse(localStorage.getItem("fta-day0-v1")||"{}")}catch{return {}}}
function isUnknown(text){const t=(text||"").trim().toLowerCase().replace(/[’']/g,"'");return !t||/^(i\s+)?(don't|do not|dont)\s+(know|remember|understand)(\b|\s)/.test(t)||/^no\s+(idea|knowledge)\b/.test(t)||/^unknown\b/.test(t)}
function inspectAnswer(text,terms){if(isUnknown(text))return{state:"not-demonstrated",hits:0,total:terms.length};const t=(text||"").toLowerCase();const hits=terms.filter(x=>t.includes(x)).length;return{state:hits?"concept-match":"unreviewed",hits,total:terms.length}}
function inspectDay0(){const a=getAnswers(),domains={};Object.entries(FTA_RUBRIC).forEach(([key,d])=>{const items=d.qs.map(n=>inspectAnswer(a["q"+n],d.terms[n]||[]));domains[key]={label:d.label,total:items.length,notDemonstrated:items.filter(x=>x.state==="not-demonstrated").length,conceptMatches:items.filter(x=>x.state==="concept-match").length,unreviewed:items.filter(x=>x.state==="unreviewed").length,status:"REVIEW REQUIRED"};});return{domains,generated:new Date().toISOString(),note:"Day 0 is diagnostic evidence. Automated inspection identifies explicit unknown answers and concept matches only; it does not assign competence percentages."}}
function saveScore(){const r=inspectDay0();try{localStorage.setItem("fta-skills-v1",JSON.stringify(r))}catch{}return r}