const FTA_RUBRIC={
networking:{label:"Networking",qs:[1,2,3,4,5,6,7,8,9,10],terms:{
1:["router","gateway","different subnet","different network","no"],2:["layer 2","mac","router","ip","layer 3"],3:["dns","ip","arp","tcp"],4:["ip","mac"],5:["access","vlan","trunk","multiple","802.1q"],6:["routing","router","layer 3","svi"],7:["loop","broadcast"],8:["192.168.50.64","192.168.50.95","192.168.50.65","192.168.50.94","30"],9:["tcp","connection","reliable","udp","connectionless"],10:["443","port","firewall","service","listen"]}},
linux:{label:"Linux",qs:[11,12,13,14,15],terms:{11:["ip addr","ip a","ifconfig"],12:["grep","find"],13:["grep","find","systemctl","journalctl"],14:["ss","netstat","5432","listen"],15:["chmod","permission","chown","owner","sudo"]}},
sql:{label:"SQL / PostgreSQL",qs:[16,17,18,19,20],terms:{16:["select","from","servers","where","status","down"],17:["unique","identify","row"],18:["table","join","related"],19:["select","read","update","delete"],20:["service","port","5432","firewall","network","listen"]}},
bms:{label:"BMS / BACnet",qs:[21,22,23,24,25],terms:{21:["sensor","point","trend","communication","controller"],22:["alarm","trend","point"],23:["protocol","building","automation","communication"],24:["analog input","analog output","binary input","binary output"],25:["one","device","network","power","controller","communication"]}},
troubleshooting:{label:"Troubleshooting",qs:[26],terms:{26:["hypothesis","test","443","firewall","service","listen","next"]}}
};
function getAnswers(){try{return JSON.parse(localStorage.getItem("fta-day0-v1")||"{}")}catch{return {}}}
function termScore(text,terms){const t=(text||"").toLowerCase();if(!t.trim())return 0;let hits=terms.filter(x=>t.includes(x)).length;let ratio=hits/terms.length;let depth=t.trim().split(/\s+/).length;let depthFactor=depth>=35?1:depth>=18?.85:depth>=8?.65:.4;return Math.min(100,Math.round((ratio*.75+depthFactor*.25)*100));}
function scoreDay0(){const a=getAnswers(),domains={};Object.entries(FTA_RUBRIC).forEach(([key,d])=>{const vals=d.qs.map(n=>termScore(a["q"+n],d.terms[n]||[]));domains[key]={label:d.label,score:Math.round(vals.reduce((x,y)=>x+y,0)/vals.length),answered:vals.filter(v=>v>0).length,total:vals.length};});const all=Object.values(domains);return{domains,overall:Math.round(all.reduce((s,d)=>s+d.score,0)/all.length),generated:new Date().toISOString(),note:"Automated baseline estimate. Review with Elsa for reasoning quality and final calibration."};}
function saveScore(){const r=scoreDay0();localStorage.setItem("fta-skills-v1",JSON.stringify(r));return r;}